### ISSUE TITLE
Select all fields by default, when opening a file

### ISSUE THREAD

**Issue by tobias-hd** [mukunku/ParquetViewer#10]
When opening a parquet file, ParquetViewer first launches a popup "Select fields to load", where you either can confirm to load all fields, or select the fields you want.

In all use cases relevant for me, I want to display all fields. Hence I'm wondering if it would be possible to skip this popup all together? It's just inconvenient to always confirm the "All fields...", before you see any data.

Maybe skipping this popup can become a configuration option somewhere?

**Comment by mukunku** [comment]
This can be achieved by adding an additional radio button such as 'All Fields (Don't Ask Again)'. But this will only be valid for the current session as the ParquetViewer does not store any user settings any where at this time.

**Comment by tobias-hd** [comment]
Hmm, I think that might not be an optimal solution, since I rarely open multiple parquet-files with the same window of ParquetViewer.

What about introducing a maximum number of columns (e.g., 10), below which all columns are immediately displayed by default, without the popup?

**Comment by mukunku** [comment]
10 would be sort of a 'magic number' in this case. It might work for you, but not others.

**Comment by mukunku** [comment]
This feature has been added in the latest release (#21)
