### ISSUE TITLE
[FEAT] IO Unblock?

### ISSUE THREAD

**Issue by sequencerr** [mukunku/ParquetViewer#101]
I'm just viewing file. Why it's blocked?(
Maybe better read to memory and release?

While opened file in app:
```js
[Error: EBUSY: resource busy or locked, open 'C:\df.parquet'] {
  errno: -4082,
  code: 'EBUSY',
  syscall: 'open',
  path: 'C:\df.parquet'
}
```

**Comment by mukunku** [comment]
Parquet files are usually multiple gigabytes in size. So the program is optimized for those use cases. I don't have any plans to add logic to load the entire file into memory so we don't acquire a read lock on it.
