### ISSUE TITLE
The query doesn't not seem to be valid. Please try again cannot find column 'user_name'

### ISSUE THREAD

**Issue by MMirabito** [mukunku/ParquetViewer#103]
**Parquet Viewer Version**
2.10.1.1

**Where was the parquet file created?**
Python

```python
def saveAsParquet(): 
    print(f"Saving...")    
    print(f"Parquet format: [{PARQUET_FILE}]")    
    
    # Load the text file into a DataFrame  Assuming the delimiter is '|'
    df = pd.read_csv(MERGED_FILE, sep='|', encoding='latin1',dtype='str')
    df.to_parquet(PARQUET_FILE)

    print(f"Completed!")  
```
**Sample File**
I cannot 

**Describe the bug**
When I try to add a where clause **"The query doesn't not seem to be valid. Please try again cannot find column 'user_name'"**
However, I can query only using the first column DBUSID. What am I doing wrong?
**Screenshots**
![2024-03-26_20-31-54](https://github.com/mukunku/ParquetViewer/assets/23298288/c65b4d4e-c5a1-4131-b07b-07f110ab6e7d)

**Additional context**

Any help is greatly appreciated.

Thanks,
max

Note: This tool relies on the [parquet-dotnet](https://github.com/aloneguid/parquet-dotnet) library for all the actual Parquet processing. So any issues where that library cannot process a parquet file will not be addressed by us. Please open a ticket on that library's repo to address such issues.

**Comment by mukunku** [comment]
Can you share your parquet file's metadata? You can hit `Ctrl + M` or go to `Tools -> Metadata Viewer`

**Comment by MMirabito** [comment]
HI @mukunku, I think figured out what the issue is. It came to me as I was waking up. 

My original file was formatted with the right padding with spaces to make the data set look easy to read if you open it in Notepad. This also included the column names. and when I removed the padding it started working.

![2024-03-27_06-48-55](https://github.com/mukunku/ParquetViewer/assets/23298288/3a1eb5f8-8741-491d-a34b-19d5c700ddcc)

Thanks again for reaching out. BTW nice software very easy to use and run.  

max

**Comment by mukunku** [comment]
Glad it's working for you and thanks for the feedback 👍🏼 

Keep in mind you can query column names with spaces in them as well by wrapping the column name in brackets. Example: `[user_name ]` . This is mentioned in the wiki under [Escaping Field Names](https://github.com/mukunku/ParquetViewer/wiki/Running-Queries#escaping-field-names)

**Comment by MMirabito** [comment]
thank you for the tip

max
