### ISSUE TITLE
[BUG] Opening folder with `_SUCCESS` files causes exception

### ISSUE THREAD

**Issue by mukunku** [mukunku/ParquetViewer#104]
This line in the code is causing the following exception:
https://github.com/mukunku/ParquetViewer/blob/d2b0fad71a822bf18e3180f04e1b0f7b9393c8cf/src/ParquetViewer.Engine/ParquetEngine.cs#L137

> An item with the same key has already been added. Key: _SUCCESS
> at System.Collections.Generic.Dictionary\`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
>    at System.Collections.Generic.Dictionary\`2.Add(TKey key, TValue value)
>    at ParquetViewer.Engine.ParquetEngine.OpenFolderAsync(String folderPath, CancellationToken cancellationToken)
>    at ParquetViewer.MainForm.OpenFieldSelectionDialog(Boolean forceOpenDialog)
>    at ParquetViewer.MainForm.openFolderToolStripMenuItem_Click(Object sender, EventArgs e)
>    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
>    at InvokeStub_SendOrPostCallback.Invoke(Object, Object, IntPtr*)
>    at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

Ideally we should capture the relative file paths which will be unique as opposed to just the file name.

**Comment by brentbundang** [comment]
[Improve error tracking by recording relative paths for skipped files #105](https://github.com/mukunku/ParquetViewer/pull/105)

**Comment by mukunku** [comment]
Thanks for fixing this 🙌🏼
