### ISSUE TITLE
Would it be possible to display the schema?

### ISSUE THREAD

**Issue by pdesmarets** [mukunku/ParquetViewer#11]
Possibly also other metadata.  Thanks!

**Comment by pdesmarets** [comment]
Another viewer proposes this, where the schema is visible.  Having data types is a good enrichment of the experience, particularly with logical type annotations:
![image](https://user-images.githubusercontent.com/10139210/63716872-48230a80-c847-11e9-8a0f-e5170e095729.png)

**Comment by mukunku** [comment]
Thanks for the idea. I added a way to get the SQL Create Table script for an open parquet file (#21)

![image](https://user-images.githubusercontent.com/4502154/99345623-b2ff9d80-2860-11eb-96cb-901321d1dbb2.png)
