### ISSUE TITLE
[FEAT] Show nanoseconds

### ISSUE THREAD

**Issue by buybackoff** [mukunku/ParquetViewer#116]
**Describe the feature you'd like to be added to Parquet Viewer**

Hello! Could you preserve and show nanoseconds, preferably with some delimiter, e.g. `...19:00:01.123_456_789Z`?

I'm not familiar with this code and presumably for a maintainer that will be fast & simple. But if not, will you be able accept a PR and release a new version with that soon?

**Share why this feature would be a good addition to the utility**
Current presentation loses information that is available in Parquet

**Comment by mukunku** [comment]
Thank a lot for this idea. I updated the `Edit → Date Format →  ISO 8601` date format to include the most precision available: `yyyy-MM-dd HH:mm:ss.FFFFFFF` in [v3.2.0.0](https://github.com/mukunku/ParquetViewer/releases/tag/v3.2.0.0).

`FFFFFFF` here being: ten millionths of a second in a date and time value. 

 I also added a `Edit → Date Format → Custom...` option just in case to see if users prefer that.
