### ISSUE TITLE
[BUG] Map results in scrambled data.

### ISSUE THREAD

**Issue by 0xSheller** [mukunku/ParquetViewer#122]
**Parquet Viewer Version**

 latest release (3.1.0)

**Where was the parquet file created?**

Pyarrow

**Sample File**
[sample.zip](https://github.com/user-attachments/files/18070336/sample.zip)!

**Describe the bug**

My schema includes: 

`pa.map_(pa.string(), pa.string()))  # Flattened dictionary`

This results in data being scrambled and overflows to the next row in parquet viewer. 

An example screenshot is attached, the first row should be: 

`{'id': '0', 'raw_record': {'email': 'collinsnathan@example.org', 'name': 'Katelyn Jacobson'}}`

Except, the raw_record over flows to the second row, so the first row will have `'email': 'collinsnathan@example.org'` and the second row will have `'name': 'Katelyn Jacobson'`. 

**Screenshots**
![image](https://github.com/user-attachments/assets/0a50f71d-7587-4894-a8ea-94fd62feec7d)

**Additional context**
Script to generate test data:

```Python
import pyarrow as pa
import pyarrow.parquet as pq
from faker import Faker

fake = Faker()

output_schema_parquet = pa.schema([
    ("id", pa.string()),
    ("raw_record", pa.map_(pa.string(), pa.string()))
])

data = []
for i in range(1000):
    data.append({
        'id': str(i),
        'raw_record': {
            'email': fake.email(),
            'name': fake.name()
        }
    })

print(data[0])

# Convert list of dicts into columnar dict
columns = {
    'id': [record['id'] for record in data],
    'raw_record': [record['raw_record'] for record in data],
}

table = pa.Table.from_pydict(columns, schema=output_schema_parquet)

with pq.ParquetWriter('sample.parquet', table.schema, use_dictionary=True, compression='snappy') as writer:
    writer.write_table(table)
```

My use-case is obviously more complex than this. I just made a minimum reproducible version of my file.

**Comment by mukunku** [comment]
Thanks a lot for reporting this issue and providing code + sample files. [Version 3.2.0.0](https://github.com/mukunku/ParquetViewer/releases/tag/v3.2.0.0) fixes this bug now. 
![{A9C37E06-F177-4FDD-A65F-9075A6209ED3}](https://github.com/user-attachments/assets/67c17bc8-b893-4a43-b628-794d178ecfbc)
