### ISSUE TITLE
Severity	Code	Description	Project	File	Line	Suppression State Error		The expression "[System.Version]::Parse('')" cannot be evaluated. Version string portion was too short or too long.

### ISSUE THREAD

**Issue by sharma1234** [mukunku/ParquetViewer#13]
Hello, I'm getting below error while building project. Please suggest what to do in this issue.

**Severity	Code	Description	Project	File	Line	Suppression State
Error		The expression "[System.Version]::Parse('')" cannot be evaluated. Version string portion was too short or too long.	ParquetFileViewer			

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0012	The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.	ParquetFileViewer	C:\Users\ssharma1\ParquetViewer\src\ParquetFileViewer\UtilityMethods.cs	16	Active**

![Capture](https://user-images.githubusercontent.com/3724533/75243269-919ce400-57ef-11ea-8793-a9d46552eb47.PNG)

**Comment by mukunku** [comment]
What version of visual studio are you using?

**Comment by sharma1234** [comment]
> What version of visual studio are you using?

![Capture](https://user-images.githubusercontent.com/3724533/75310366-ceadb880-5879-11ea-806f-fa3dfcae0d18.PNG)

**Comment by mukunku** [comment]
Visual Studio 2015 does not support the required versions of .Net Standard and C# 7. Please use Latest VS2017 (15.9) or VS2019. Both are free with the Community Edition: https://visualstudio.microsoft.com/downloads/
