### ISSUE TITLE
crash loading a file with not null column

### ISSUE THREAD

**Issue by voltcode** [mukunku/ParquetViewer#14]
I created a parquet file with two columns - nullable int and non nullable int.
when I try to view it in ParquetViewer, it crashes when I select the non nullable int.
loading the same file with:

http://parquet-viewer-online.com/

is fine 

[test.zip](https://github.com/mukunku/ParquetViewer/files/4443156/test.zip)

attached is the problematic file.

crash image:
![image](https://user-images.githubusercontent.com/5236618/78652209-b9d53380-78c1-11ea-8a6b-8d50df501d0c.png)

**Comment by mukunku** [comment]
Thanks for the detailed description and sample file. I pushed a fix for you: https://github.com/mukunku/ParquetViewer/releases/tag/v2.1

**Comment by voltcode** [comment]
thanks, it works great!
