### ISSUE TITLE
View split files

### ISSUE THREAD

**Issue by Technetium1** [mukunku/ParquetViewer#15]
I've found some data named like `XXXXX_UserData_0001.parquet` up to `XXXXX_UserData_0005.parquet`
When opening any of the files I get this error: 
![image](https://user-images.githubusercontent.com/9877150/81536946-6891e700-933a-11ea-9731-f478b9b9eeea.png)
Is it possible to open any of these files?

**Comment by mukunku** [comment]
It seems the [Parquet.net](https://github.com/elastacloud/parquet-dotnet) library that we use can't open the files so nothing can be done on our end unfortunately. Are you able to read a single one of any of these files in some other system (i.e. try opening a single part in another system)?

**Comment by Technetium1** [comment]
Unfortunately I have not been able to. I will reopen this issue in the future if any progress is made.
