### ISSUE TITLE
Reader for compression '4' not supported

### ISSUE THREAD

**Issue by AmosDinh** [mukunku/ParquetViewer#18]
Is there a possibility that this could be implemented?
My files are compressed using pandas and brotli compression. Compression gzip works.
`df.to_parquet(path=saveurl, compression='brotli')`
![image](https://user-images.githubusercontent.com/39965380/97703326-bbaa5280-1ab0-11eb-8950-bb49dcbd6179.png)

**Comment by mukunku** [comment]
I think this is a limitation with the Parquet.NET library. Can you open an issue ticket there?

https://github.com/elastacloud/parquet-dotnet/issues
