### ISSUE TITLE
Path Separator issue

### ISSUE THREAD

**Issue by Sudhir87** [mukunku/ParquetViewer#2]
Hi,

I would like to understand what are the special characters used for path separator as I am getting the below error? Attaching the column list for your reference. Kindly assist.

![image](https://user-images.githubusercontent.com/41491841/43026747-b52ecc12-8c94-11e8-830e-a17e3aef0138.png)

[Lead_Test1.zip](https://github.com/mukunku/ParquetViewer/files/2215562/Lead_Test1.zip)

**Comment by mukunku** [comment]
Closing this issue as "Will not be fixed"
