### ISSUE TITLE
Error: Sum of the columns FillWeight values cannot exceed 65535, when trying to load a parquet file with a large number of columns

### ISSUE THREAD

**Issue by neil-hucker-seequent** [mukunku/ParquetViewer#22]
Version: 2.2.7625.41329
Parquet file created by pyarrow

Sample File (Note that the data in this file is junk data so in this case the values are mostly meaningless) :
[NewRows_1_30_2009cols.zip](https://github.com/mukunku/ParquetViewer/files/5599365/NewRows_1_30_2009cols.zip)

Problem:
When I try to load a parquet file that contains > 4000 columns I receive an error: " Sum of the columns FillWeight values cannot exceed 65535" when it tries to add columns to the DataGridView forms object. 
The Grid view seems to load ~656 of my 4666 columns into the header row within the grid, before it throws the error and then ceases to load anything else into the grid.

To replicate:
1. Try to open the attached parquet file.

![image](https://user-images.githubusercontent.com/69882763/100284458-182b5f80-2fd4-11eb-9ef8-56ec5cf9c1e7.png)

I have successfully been able to open the file with another parquet viewer (within an IDE) so it seems that the parquet file is valid.

![image](https://user-images.githubusercontent.com/69882763/100284854-c1725580-2fd4-11eb-9aa3-ff84ff3caae0.png)
![image](https://user-images.githubusercontent.com/69882763/100285085-2037cf00-2fd5-11eb-98ae-743708c2e936.png)

**Comment by mukunku** [comment]
Need to take a look to see if these many columns can actually be handled in winforms.

**Comment by mukunku** [comment]
The FillWeight issue has been resolved as of [v2.2.1](https://github.com/mukunku/ParquetViewer/releases/tag/v2.2.1). Let me know if you still experience any issues.
