### ISSUE TITLE
[FEATURE-REQUEST] Support for Map datatype

### ISSUE THREAD

**Issue by rr-on-gh** [mukunku/ParquetViewer#3]
Currently there is no support for data structures like Map, Lists etc. and an error message is thrown when such files are opened. Can Map datatype be supported?

**Comment by mukunku** [comment]
Can you please share the error message shown? Even if the utility can't display these types I believe it can be changed so that it at least shows the other non Map/List fields.

**Comment by raks81** [comment]
I'll paste the error message in a bit. So the file can still be loaded by not selecting the field that has Map values when the file is first loaded. I was wondering if support to view Map could be added. I guess it doesn't fit well UI-wise in the current tabular format. but even if we could just build a string out of the Map and show that as column, it would be helpful.

**Comment by ShubhamBelwal** [comment]
![image](https://user-images.githubusercontent.com/36201797/51896839-5a34eb80-23d3-11e9-9e23-fce8b5abde24.png)

**Comment by ShubhamBelwal** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/36201797/51896839-5a34eb80-23d3-11e9-9e23-fce8b5abde24.png)

I get this message when I try to open a file containing Map type columns.

**Comment by ShubhamBelwal** [comment]
Any update on the support for Map Types?

**Comment by pdesmarets** [comment]
I am also interested in seeing support for logical types.  Actually all possible data types...

**Comment by mith-emsa** [comment]
I would also be interested in support for map types, as well as struct types. Do you think you will support this soon?

**Comment by mukunku** [comment]
Can you share a sample file? That would be very helpful.

**Comment by pdesmarets** [comment]
There are all kinds of sample files of different nature here https://github.com/apache/parquet-testing/tree/master/data

**Comment by mukunku** [comment]
Just an update: In the newer versions it should be possible to open a file with unsupported field types but the unsupported fields cannot be selected for display in the UI for now.

**Comment by mukunku** [comment]
List and Array type supported has been added #37. Hopefully will add MAP some time soon as well.

**Comment by mukunku** [comment]
Non-nested map and list support is available now with [v2.7.0](https://github.com/mukunku/ParquetViewer/releases/tag/v2.7.0)

Going to call that a win and close out this issue.
