### ISSUE TITLE
[FEAT] Display null values as NULL in italic (or something else)

### ISSUE THREAD

**Issue by felipepessoto** [mukunku/ParquetViewer#31]
**Describe the feature you'd like to be added to Parquet Viewer**
When the value is null, display the word NULL in italic

**Share why this feature would be a good addition to the utility**
Currently it is impossible to distinguish between empty string and NULL value

**Comment by mukunku** [comment]
Thanks for the idea. This is available as of: [v2.3.1](https://github.com/mukunku/ParquetViewer/releases/tag/v2.3.1) now

**Comment by felipepessoto** [comment]
Thanks for doing it so fast
