### ISSUE TITLE
Add support for List type fields

### ISSUE THREAD

**Issue by emanueol** [mukunku/ParquetViewer#33]
**Parquet Viewer Version**
2.3.0.40676

**Where was the parquet file created?**
AWS EMR > Apache Spark

**Sample File**
cant do, its 22MB with sensitive information and i dont have control of producer.

**Describe the bug**
Parquet contains a field which is a nested table (array of strings).. so I guess ParquetViewer is unable to open these type of parquets.
I cant share parquet data file, but im attaching detailed error popup screenshot - basically its refering to the nested field.

**Screenshots**
![parquet-error-nestedtable](https://user-images.githubusercontent.com/8422412/113454001-231d5300-93ff-11eb-8bba-c6a676dcf809.jpg)
![parquet-error-nestedtable2](https://user-images.githubusercontent.com/8422412/113454009-26b0da00-93ff-11eb-9c7b-e0ffaf220c74.jpg)

**Additional context**

Note: This tool relies on the [parquet-dotnet](https://github.com/elastacloud/parquet-dotnet) library for all the actual Parquet processing. So any issues where that library cannot process a parquet file will not be addressed by us. Please open a ticket on that library's repo to address such issues.

**Comment by mukunku** [comment]
Support for List types have been added as of [v2.4](https://github.com/mukunku/ParquetViewer/releases) (nested lists still not supported though):
![image](https://user-images.githubusercontent.com/4502154/121813576-8f57d680-cc3a-11eb-9ba2-6a778873f9e0.png)

Let me know how it works for your file. If you experience any issues please comment on #37 

Here are some sample files with list values:
* [list_columns.zip](https://github.com/mukunku/ParquetViewer/files/6644171/list_columns.zip)
* [users.zip](https://github.com/mukunku/ParquetViewer/files/6644172/users.zip)
