### ISSUE TITLE
[FEATURE-REQUEST] Ability to open partitioned files

### ISSUE THREAD

**Issue by tigerhawkvok** [mukunku/ParquetViewer#35]
**Parquet Viewer Version**

2.3.1.41849

**Where was the parquet file created?**

Pandas -> pyarrow

`dfStore.to_parquet(BUILDINGS_OUTPUT_FILE, partition_cols= ["type"])`

**Sample File**

[pv_bugdemo.parquet.zip](https://github.com/mukunku/ParquetViewer/files/6594608/pv_bugdemo.parquet.zip)

**Describe the bug**

A partitioned file that is actually a folder with several subfiles should be supported. This probably involves checking if the "file" is actually a directory then traversing the tree to read the individual constituent files.

Note: This tool relies on the [parquet-dotnet](https://github.com/elastacloud/parquet-dotnet) library for all the actual Parquet processing. So any issues where that library cannot process a parquet file will not be addressed by us. Please open a ticket on that library's repo to address such issues.

**Comment by mukunku** [comment]
This is a big feature to implement. Not sure if it can be done as it's really complicated. Leaving this ticket open for now in case anyone wants to tackle this behemoth.

**Comment by mukunku** [comment]
Support to open partitioned files has been finally added! https://github.com/mukunku/ParquetViewer/releases/tag/v2.6.0
