### ISSUE TITLE
[FEAT] Support for the ZSTD compression format

### ISSUE THREAD

**Issue by enricodetoma** [mukunku/ParquetViewer#38]
**Describe the feature you'd like to be added to Parquet Viewer**
Support for the ZSTD compression format (and possibly other additional compression formats).

**Share why this feature would be a good addition to the utility**
I have some Parquet files compressed with ZSTD, I get the error in the screenshot below,

**Screenshots**
![image](https://user-images.githubusercontent.com/464156/122178606-02558d00-ce87-11eb-809a-b6079df21cd6.png)

**Comment by mukunku** [comment]
Thanks for reporting this issue. Unfortunately this is a limitation of the parquet.net library that we're using internally. It seems there's already an [open ticket](https://github.com/aloneguid/parquet-dotnet/issues/40) there for ZSTD support. So this is probably not something that we would try and do in this project.

**Comment by enricodetoma** [comment]
Thanks, now I understand perfectly that the issue belongs to the parquet.net library. I close the issue.

**Comment by maximethebault** [comment]
Looks like https://github.com/aloneguid/parquet-dotnet/issues/40 has been resolved in version 4.1.0

**Comment by mukunku** [comment]
Thanks for the heads up @maximethebault . I just released [v2.4.2](https://github.com/mukunku/ParquetViewer/releases/tag/v2.4.2) with that package version 🙌🏼

**Comment by maximethebault** [comment]
It works perfectly, thanks a lot!
