### ISSUE TITLE
[FEATURE REQUEST] Ability to read parquet files compressed with "zstd"

### ISSUE THREAD

**Issue by san-r** [mukunku/ParquetViewer#39]
Parquet files are nowadays often saved with ZSTD compression since its decompression speed and hence reading speed is very significantly faster than GZIP standard which is currently supported by ParquetViewer.

We regularly use Apache Arrow and plan to use ZSTD compression instead of GZIP as documented in the webpage https://arrow.apache.org/docs/r/reference/write_parquet.html. It would be great if we could continue to use ParquetViewer.

Currently attempting to open ZSTD compressed parquet file results in an error as shown in this screenshot:
![image](https://user-images.githubusercontent.com/45727825/128663066-38b95568-affe-458c-a31e-94f38803b716.png)

It is requested that support for ZSTD compression be incorporated in future versions of ParquetViewer.

**Comment by mukunku** [comment]
Unfortunately we already had this discussion in #38  

I'll copy my response from there, here:
> Thanks for reporting this issue. Unfortunately this is a limitation of the parquet.net library that we're using internally. It seems there's already an [open ticket](https://github.com/aloneguid/parquet-dotnet/issues/40) there for ZSTD support. So this is probably not something that we would try and do in this project.

I kind of doubt that zstd support will ever get added to be honest. The Parquet.Net repo isn't very active anymore.

**Comment by aloneguid** [comment]
@mukunku but you're welcome to raise a PR and add it. The core of the library is stable and I'm only adding features when I personally need it, can't work for free all the time :)
