### ISSUE TITLE
[FEATURE REQUEST] Display timestamp fields in human-intelligible format

### ISSUE THREAD

**Issue by san-r** [mukunku/ParquetViewer#40]
ParquetViewer is the best parquet file viewer. However, it shows 'timestamp' fields in Unix epoch (or Unix time or POSIX time or Unix timestamp), i.e., the number of seconds that have elapsed since January 1, 1970 (midnight UTC/GMT). For example,

![image](https://user-images.githubusercontent.com/45727825/129145067-6b71831c-c534-4239-8988-2c38eddbabc6.png)

The 'date' field is displayed just fine. It is requested that 'date-time' field be made viewable in human-intelligible format.

Meanwhile, I've posted a request at https://stackoverflow.com/questions/68741520/date-time-timestamp-field-in-parquet-file-shown-as-numbers-in-parquet-file-vie to see if something (like formatting change) could be done in R environment before exporting to parquet format so that it displays 'timestamp' field in human-intelligible format in ParquetViewer.

**Comment by mukunku** [comment]
Can you share a sample parquet file? This should be doable

**Comment by san-r** [comment]
Sure, here is the same parquet file shown in the screenshot in original post: [testFyl.zip](https://github.com/mukunku/ParquetViewer/files/6983512/testFyl.zip)

Thanks for your efforts.

**Comment by mukunku** [comment]
Give this a shot and let me know if it works for you: 
[ParquetViewer.zip](https://github.com/mukunku/ParquetViewer/files/6985407/ParquetViewer.zip)

I compared the values against https://www.online-toolz.com/tools/unix-timestamp-to-date.php and it looks okay to me. (Keep in mind this website converts to your local timezone whilst in Parquet Viewer it will remain as UTC.

**Comment by san-r** [comment]
Excellent job. This version nicely shows the timestamps. But I must apologize for providing an inadequate sample file which had time only upto hours and minutes and omitted out seconds. It is enough for displaying in ParquetViewer in almost all cases.

But just in case it is needed, here is a second sample parquet file which has seconds also:  [sample2.zip](https://github.com/mukunku/ParquetViewer/files/6985730/sample2.zip)

The above version of ParquetViewer shows it as:

![image](https://user-images.githubusercontent.com/45727825/129430763-f44b8516-2c36-4b42-a6fe-8486e2a4b752.png)

While in RStudio, where I created the sample file, it shows the seconds also:

![image](https://user-images.githubusercontent.com/45727825/129430802-9f30ca36-ea6d-4626-a65b-1034ae82cd79.png)

I should reiterate that the current version shows timestamps properly and is adequate for me. But I thought that I should inform anyway.

Thanks again for your efforts.

**Comment by mukunku** [comment]
This is really helpful, thanks. I'll take a look at this file too before releasing v2.3.2 officially.

**Comment by mukunku** [comment]
So I took a look and I think the default formatting for dates doesn't include the seconds. If you switch the date format to ISO 8601 you can see the seconds:
![image](https://user-images.githubusercontent.com/4502154/129453653-86a23da0-492c-40d3-b8dc-0572dfee6808.png)
