### ISSUE TITLE
[FEAT] Add metadata viewer

### ISSUE THREAD

**Issue by mikestaib** [mukunku/ParquetViewer#42]
Would it be possible to add an element to view the custom file metadata? 

This would be useful for accessing additional fields that may be stored as metadata in the file.

**Comment by mukunku** [comment]
This needs some investigation and has been on my mind. The parquet-dotnet library we use internally does give us access to the Thrift metadata. But I'm not sure how easy it is to extract that info and display it in a user friendly format.

**Comment by mukunku** [comment]
I put a dent into this and added a preliminary metadata viewer in v2.3.3 

Closing this ticket for now and can re-visit in the future maybe.
