### ISSUE TITLE
[FEAT] Double-clicking a parquet file should open ParquetViewer with the contents of file 

### ISSUE THREAD

**Issue by sparky2708** [mukunku/ParquetViewer#48]
**Describe the feature you'd like to be added to Parquet Viewer**
 When associating ParquetViewer as default app for parquet files, double clicking the parquet file should open ParquetViewer with the contents of file. Currently, it just opens ParquetViewer with no file contents.

Note: There are no guarantees your feature will be implemented.

**Comment by mukunku** [comment]
That's strange. Double click support has been there for a long time and when I test it it works for me:
![double_click](https://user-images.githubusercontent.com/4502154/148144653-58aee767-70b3-4f14-a98c-0e37d623f3bc.gif)

**Comment by sparky2708** [comment]
I am doing this on Windows 10. What you’re showing looks like some flavor of Unix

**Comment by mukunku** [comment]
Nope, it's Windows 10
![image](https://user-images.githubusercontent.com/4502154/148217478-72b08299-4d2f-44fb-9a00-11fb08812d61.png)

Any chance you could record the error happening?

**Comment by mukunku** [comment]
Closing out this issue.
