### ISSUE TITLE
[FEAT] Adjust column size to data/column name

### ISSUE THREAD

**Issue by carlosfrutos** [mukunku/ParquetViewer#49]
**Describe the feature you'd like to be added to Parquet Viewer**
It would be great to be able to adjust automatically the size of all columns to the size of the data and/or the column name. When opening parquet files with lots of double type columns, you have to adjust individually each column to be able to see the whole number (with the E-# at the end). That way you can easily view column values and compare them between columns.

Adjusting by column contents will make all column sizes to match maximum length of a column value
Adjusting by column names will make all column sizes to match the length of the column name
Adjusting by column names and contents will make all column sizes to match the biggest length of either the column name or the column values

**Share why this feature would be a good addition to the utility**
It will improve usability and data readability

**Screenshots**
I will try to put here a proposal for the menu items:

```
Tools
|  Adjust columns > | Column contents
                    | Column names
                    | Column names and contents


```

I just found your tool and I think it's great!!

Thank you for the effort!

Best regards,

Carlos

**Comment by mukunku** [comment]
I added the options under Edit -> Column Sizing : https://github.com/mukunku/ParquetViewer/releases/tag/v2.3.6
Let me know how it works.

**Comment by carlosfrutos** [comment]
Looks great to me now!

Thank you very much!!
