### ISSUE TITLE
[FEAT] Display Rowgroup info

### ISSUE THREAD

**Issue by felipepessoto** [mukunku/ParquetViewer#67]
In the metadata viewer we could have a tab with row group info. Row group count, the size and number of rows of each of them

**Comment by mukunku** [comment]
Thanks for the idea. I added the row group count and individual row group info to the Thrift metadata in the metadata viewer. 

You can check it out here: https://github.com/mukunku/ParquetViewer/releases/tag/v2.5.1

Row group info will be at the bottom of the json:
![image](https://user-images.githubusercontent.com/4502154/215312449-db813b21-f8cc-4ee7-bcdf-aeeb0bbb454f.png)
