### ISSUE TITLE
Support opening a .parquet file directly from Windows Explorer

### ISSUE THREAD

**Issue by tobias-hd** [mukunku/ParquetViewer#7]
Thanks a lot for providing this Viewer! 

I'm wondering if it should be possible to open a .parquet file in Windows Explorer directly with a mouse click. Currently, when I do this, the ParquetViewer starts up, but with an empty window. I then need to open the file manually by pressing main menu->Open, and browsing through the directory structure.

Maybe it's just a configuration that's missing on my side?
Otherwise, this is a kind feature request :)

Tobias

**Comment by mukunku** [comment]
v1.1 now supports this feature. v1.0+ supports dragging and dropping files directly onto the tool as well.

**Comment by tobias-hd** [comment]
Thanks a lot! That was very quick!
