### ISSUE TITLE
[BUG] Cannot open file because of missing column, but column is present.

### ISSUE THREAD

**Issue by MCRE-BE** [mukunku/ParquetViewer#70]
**Parquet Viewer Version**
What version of Parquet Viewer are you experiencing the issue with?
2.5.1.0

**Where was the parquet file created?**
Pandas Python - 1.5.3

**Sample File**
[Example.zip](https://github.com/mukunku/ParquetViewer/files/10908532/Example.zip)

**Describe the bug**
Cannot open the file, but file can be opened in Python as the column flagged as missing is present. Likely because of a trailing "." (as that is the only mismatch between the file and the bugreport)
<img src="https://user-images.githubusercontent.com/99316631/223400700-10c51bbd-0c1a-4579-b3ec-6b15ce840e58.png" width="300">

**Screenshots**
![image](https://user-images.githubusercontent.com/99316631/223401601-120c6a66-eae8-4590-9ea7-6515546d0c1e.png)

**Comment by mukunku** [comment]
Looks like the underlying [parquet.net](https://github.com/aloneguid/parquet-dotnet) library has an issue with column names ending in periods. I'm going to see if I can take a look to see if it's simple enough for me to fix. Maybe next week.

I'd normally open a bug ticket in that repo to see if someone else can get to it but I'm feeling a bit lazy 🙂 . If you're up for it opening a bug ticket there might significantly speed up getting a fix for this.

**Comment by MCRE-BE** [comment]
Top.

I'll open a bug report after my holidays 😇

**Comment by mukunku** [comment]
Thanks so much for following up on this. I updated the parquet-dotnet library to v4.6.0 now and can open your file now!

https://github.com/mukunku/ParquetViewer/releases/tag/v2.6.0.1

Closing out this ticket 🙌🏼
