### ISSUE TITLE
[BUG] Error when opening file containing columns of LIST type

### ISSUE THREAD

**Issue by mughees-wyne** [mukunku/ParquetViewer#73]
**Parquet Viewer Version**
2.5.1

**Where was the parquet file created?**
pyarrow

**Sample File**
[test_file_20230120_common_ts.zip](https://github.com/mukunku/ParquetViewer/files/11148196/test_file_20230120_common_ts.zip)

**Describe the bug**
The Parquet Viewer is not able to open a file that contains columns of LIST type. In the attached file "object_data__obj_angles" is a column of LIST type but as you see in the screenshot it complains that this column doesn't exist (don't know why). However, v2.4 mentioned at https://github.com/mukunku/ParquetViewer/issues/33#issuecomment-860229328 is able to load this file without issues.

**Screenshots**
v2.5.1
![image](https://user-images.githubusercontent.com/44430863/229785052-15c5fb48-73fb-4300-b11e-3c62c28bffef.png)

v2.4
![image](https://user-images.githubusercontent.com/44430863/229787291-29012f3d-4825-4f88-beab-86a56a30abf6.png)

**Comment by mukunku** [comment]
I was able to add **non-nested** list support in v2.4. But after trying to handle nested lists I kind of gave up because implementing the dremel algorithm is beyond my skillset. Maybe I can look into adding non-nested list support again but it's known that list types don't work as mentioned in the readme.

**Comment by mughees-wyne** [comment]
> I was able to add **non-nested** list support in v2.4. But after trying to handle nested lists I kind of gave up because implementing the dremel algorithm is beyond my skillset. Maybe I can look into adding non-nested list support again but it's known that list types aren't supported in the app as mentioned in the readme.

Non-nested list support would be better than having nothing at all. It should be enough for many simple use cases.

**Comment by mughees-wyne** [comment]
Having Non-nested lists is still better then nothing. And I think single level lists are generally more widely used then nested lists so I think this support will be useful in the app.

**Comment by mukunku** [comment]
Non-nested list support is available now with [v2.7.0](https://github.com/mukunku/ParquetViewer/releases/tag/v2.7.0)

Going to close out this issue. Please feel free to re-open if you experience any issues.
