### ISSUE TITLE
[BUG] Unable to open the file which contains a nullable guid column

### ISSUE THREAD

**Issue by MarkoPielic** [mukunku/ParquetViewer#76]
**Parquet Viewer Version**
2.7.0.3

**Where was the parquet file created?**
C#

**Sample File**
[NullableGuid.zip](https://github.com/mukunku/ParquetViewer/files/11495851/NullableGuid.zip)

**Describe the bug**
Program is unable to open the file if it contains a nullable guid column.

**Screenshots**
![image](https://github.com/mukunku/ParquetViewer/assets/47854980/33885d74-b8b6-4194-ad14-8545d6e15e36)

**Additional context**
The nullable guid issue was resolved here https://github.com/aloneguid/parquet-dotnet/issues so everything needed is probably just the Parquet.Net library update.

**Comment by mukunku** [comment]
Dang, I just released 2.7.0. I'll try get a release out with a package update soon. Thanks for reporting this and the sample file; it helps with adding unit tests.

**Comment by mukunku** [comment]
This is fixed now in [v2.7.1](https://github.com/mukunku/ParquetViewer/releases/tag/v2.7.1). I added a unit test for it too. 

Closing out this ticket.
