### ISSUE TITLE
Application Error when trying to open parquet file

### ISSUE THREAD

**Issue by Uterr** [mukunku/ParquetViewer#83]
**Parquet Viewer Version**
ParquetViewer_SelfContained.exe, 2.7.1.0

**Where was the parquet file created?**
unknown

**Sample File**
https://huggingface.co/datasets/Gaivoronsky/hh-rlhf-ru-rl/tree/main/data

**Describe the bug**
When user opens file error is emitted. No stack trace given.

**Screenshots**
Standard windows dialog saying "Application stopped working"

**Additional context**
Error emitted when trying to open file:
https://huggingface.co/datasets/Gaivoronsky/hh-rlhf-ru-rl/tree/main/data

[[Note: This tool relies on the [parquet-dotnet](https://github.com/elastacloud/parquet-dotnet) library for all the actual Parquet processing. So any issues where that library cannot process a parquet file will not be addressed by us. Please open a ticket on that library's repo to address such issues.]

**Comment by mukunku** [comment]
Hi, this is a strange one. The file you provided works for me on my end:
![image](https://github.com/mukunku/ParquetViewer/assets/4502154/0c0711a5-3802-4c11-9c8a-87a06510f75b)

Is there any other information you could give to help understand why this happens on your pc?

**Comment by mukunku** [comment]
Gonna close this out for now but feel free to re-open if you can provide more details.
