### ISSUE TITLE
[FEAT] View per-column metadata

### ISSUE THREAD

**Issue by ngbrown** [mukunku/ParquetViewer#84]
**Describe the feature you'd like to be added to Parquet Viewer**

I would like the metadata viewer to show the custom key_value_metadata added to each column of the schema. PyArrow's API seems to allow this to be added at the [schema level](https://mungingdata.com/pyarrow/arbitrary-metadata-parquet-table/), while `Parquet.Net`'s [API adds](https://aloneguid.github.io/parquet-dotnet/metadata.html#column-chunk-metadata) it per row group, which is more inline with the actual [file structure](https://parquet.apache.org/docs/file-format/metadata/).

**Share why this feature would be a good addition to the utility**

I want to validate that I'm building Parquet files correctly with the data I expect. I would like to use metadata for per-column information like units and description.

**Comment by mukunku** [comment]
I added some column metadata to the row groups in https://github.com/mukunku/ParquetViewer/releases/tag/v2.7.2 . Can you check it out and see if that's good enough for your needs?

**Comment by ngbrown** [comment]
@mukunku I see the column metadata (`KeyValueMetadata`) in each row group. I like that the byte sizes of each column are now available to get an idea of how well each column is de-duplicating and compressing.

This extra information also greatly increases the line count of the metadata window (2,440 -> 78,498), so I copied the json into Visual Studio Code to make use of the collapsing and search. I may have too many row groups... Anyways doing more with the UI will have diminishing returns because other editors will do a better job. Maybe a copy button would be the extent of any change I would suggest to the metadata viewer window?

Thank you for your tool and I'm now able to use this feature request for what I needed.

**Comment by mukunku** [comment]
Thank you for the feedback. I reverted the extra info I added to the thrift metadata being shown. And added a "Copy Raw Metadata" button as you suggested. You can find this new feature available in: [v2.7.2.1](https://github.com/mukunku/ParquetViewer/releases/tag/v2.7.2.1)

Really appreciate the ideas to help make the app better. Closing out this ticket for now but feel free to reopen.
