### ISSUE TITLE
[BUG] Cannot open parquet file when column name includes "/"

### ISSUE THREAD

**Issue by tunajaw** [mukunku/ParquetViewer#94]
**Parquet Viewer Version**
What version of Parquet Viewer are you experiencing the issue with?
2.8.0

**Where was the parquet file created?**
Apache Spark, Hive, Java, C#, pyarrow, etc.
python pandas 1.5.2

**Sample File**
[ts_input.zip](https://github.com/mukunku/ParquetViewer/files/13038786/ts_input.zip)

**Describe the bug**
The Parquet Viewer is not able to open a file whose column name includes the character "/".

**Screenshots**
There is a column named `FLC K/L` in my dataset.
![image](https://github.com/mukunku/ParquetViewer/assets/55829925/dc38b2e6-b4e5-4570-92b7-ca54086af887)

![image](https://github.com/mukunku/ParquetViewer/assets/55829925/a6f693d3-be55-4bc7-a873-3dc9f0709358)

**Comment by mukunku** [comment]
Sorry for the late response. This has been fixed now in [v2.8.1.2](https://github.com/mukunku/ParquetViewer/releases/tag/v2.8.1.2)

Thanks for opening a ticket and sharing a sample file.
